export const Colors = {
  dark: {
    background: '#141414',
    foreground: '#FAFAFA',
    card: '#1E1E1E',
    cardForeground: '#FAFAFA',
    primary: '#22C55E',
    primaryForeground: '#141414',
    secondary: '#2A2A2A',
    secondaryForeground: '#FAFAFA',
    muted: '#2A2A2A',
    mutedForeground: '#A1A1A1',
    accent: '#22C55E',
    accentForeground: '#141414',
    destructive: '#EF4444',
    destructiveForeground: '#FAFAFA',
    border: '#333333',
    input: '#2A2A2A',
    ring: '#22C55E',
    overlay: 'rgba(0, 0, 0, 0.7)',
    tabBar: '#0A0A0A',
    nowPlayingBar: '#1A1A1A',
    skeleton: '#2A2A2A',
  },
  light: {
    background: '#FFFFFF',
    foreground: '#0A0A0A',
    card: '#F5F5F5',
    cardForeground: '#0A0A0A',
    primary: '#16A34A',
    primaryForeground: '#FFFFFF',
    secondary: '#E5E5E5',
    secondaryForeground: '#0A0A0A',
    muted: '#E5E5E5',
    mutedForeground: '#737373',
    accent: '#16A34A',
    accentForeground: '#FFFFFF',
    destructive: '#DC2626',
    destructiveForeground: '#FFFFFF',
    border: '#D4D4D4',
    input: '#E5E5E5',
    ring: '#16A34A',
    overlay: 'rgba(0, 0, 0, 0.5)',
    tabBar: '#FFFFFF',
    nowPlayingBar: '#F5F5F5',
    skeleton: '#E5E5E5',
  },
};

export type ThemeColors = typeof Colors.dark;
